bridge_robot:
  ros__parameters:
    agent_name: bridge_agent
    agent_id: 100
    source: robot
    dsr_input_file: ""
tf_agent:
  ros__parameters:
    agent_name: tf_agent
    agent_id: 101
    source: robot
nav_agent:
  ros__parameters:
    agent_name: nav_agent
    agent_id: 102
    source: robot
    dsr_action_name: move
    ros_action_name: "navigate_to_pose"
docking_agent:
  ros__parameters:
    agent_name: docking_agent
    agent_id: 103
    source: robot
    dsr_action_name: dock
    ros_action_name: "dock_robot"
battery_agent:
  ros__parameters:
    agent_name: battery_agent
    agent_id: 104
    source: robot
    dsr_node_name: battery
    dsr_parent_node_name: robot
    ros_topic: "/battery"
imu_agent:
  ros__parameters:
    agent_name: imu_agent
    agent_id: 105
    source: robot
    dsr_node_name: imu
    dsr_parent_node_name: robot
    ros_topic: "/imu"
