battery_agent:
  ros__parameters:
    agent_name: battery_agent
    agent_id: 2
    ros_topic: /battery
    dsr_node_name: battery
    dsr_parent_node_name: robot
laser_agent:
  ros__parameters:
    agent_name: laser_agent
    agent_id: 3
    ros_topic: /scan/filtered
    dsr_node_name: laser
    dsr_parent_node_name: base_laser_link
rgb_agent:
  ros__parameters:
    agent_name: rgb_agent
    agent_id: 4
    ros_topic: /realsense/color/image_raw
    dsr_node_name: realsense
    dsr_parent_node_name: realsense_link
rgbd_agent:
  ros__parameters:
    agent_name: rgbd_agent
    agent_id: 5
    ros_topic: /realsense/depth/image_rect_raw
    dsr_node_name: realsense
    dsr_parent_node_name: realsense_link