tf_agent:
  ros__parameters:
    agent_id: 100
    dsr_input_file: ''
    source: robot
nav_agent:
  ros__parameters:
    agent_id: 101
    source: robot
docking_agent:
  ros__parameters:
    agent_id: 102
    source: robot
battery_agent:
  ros__parameters:
    agent_id: 103
    source: robot
    dsr_node_name: battery
    dsr_parent_node_name: robot
    ros_topic: /battery
laser_agent:
  ros__parameters:
    agent_id: 104
    source: robot
    dsr_node_name: laser
    ros_topic: /scan/filtered
rgb_agent:
  ros__parameters:
    agent_id: 105
    source: robot
    dsr_node_name: realsense
    ros_topic: /realsense/color/image_raw
rgbd_agent:
  ros__parameters:
    agent_id: 106
    source: robot
    dsr_node_name: realsense
    ros_topic: /realsense/depth/image_rect_raw